/**************************************************************************/
/*  donors.gen.h                                                          */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

/* THIS FILE IS GENERATED. EDITS WILL BE LOST. */

#pragma once

inline constexpr const char *DONORS_PATRONS[] = {
	"Scorewarrior <https://scwr.gg/godot>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_PLATINUM[] = {
	"JetBrains <https://www.jetbrains.com/lp/rider-godot/>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com/>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_GOLD[] = {
	"Arm <https://www.arm.com/>",
	"Mega Crit <https://www.megacrit.com/>",
	"Prehensile Tales <https://prehensile-tales.com>",
	"Robot Gentleman <http://robotgentleman.com/>",
	nullptr,
};

inline constexpr const char *DONORS_SPONSORS_SILVER[] = {
	"Bippinbits <https://bippinbits.com/>",
	"Blobfish Games <https://www.blobfishgames.com/>",
	"Broken Rules <https://brokenrul.es>",
	"Chasing Carrots <https://www.chasing-carrots.com>",
	"Copia Wealth Studios <https://copiawealthstudios.com/>",
	"Evil Trout Inc. <https://eviltrout.com/>",
	"Games by Malcs <https://gamesbymalcs.com/>",
	"LoadComplete <https://loadcomplete.com/>",
	"Null <https://null.com/>",
	"Playful Studios <https://playfulstudios.com/>",
	"Re-Logic <https://re-logic.com/>",
	"Sentry <https://sentry.io/welcome/?utm_source=godotengine&utm_medium=paid-community&utm_campaign=gaming-fy26q3-evergreen&utm_content=static-ad-godot-eng-sponsor-trysentry>",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_DIAMOND[] = {
	"Acerola <https://www.youtube.com/@Acerola_t>",
	"ASIFA-Hollywood <https://www.asifa-hollywood.org/>",
	"Christina Coffin <https://bsky.app/profile/christinacoffin.bsky.social>",
	"Kanda <https://www.kanda.dk>",
	"Petr Kharitonov <https://petrkharitonov.com/>",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype>",
	"And 1 anonymous donor",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_TITANIUM[] = {
	"Adriaan de Jongh <https://adriaan.games>",
	"Basically Games",
	"Deloryan <https://www.deloryan.com/>",
	"Draknek & Friends <https://www.draknek.org/>",
	"Eugene Denisenko <https://craft.sc/>",
	"Garry Newman",
	"Justo Delgado Baudí <https://portfolio.mrcdk.com/>",
	"Kenney <https://kenney.nl/>",
	"Lucid Silence Games",
	"Megafauna Games <https://www.megafauna.games/>",
	"Midjiwan AB <https://www.midjiwan.com>",
	"NekTek Games <https://nektek.games/>",
	"Patrick Curry <https://patrickcurry.com/>",
	"PolyMars <https://youtube.com/@PolyMarsLIVE>",
	"Purple Moss Collectors <https://purplemosscollectors.com>",
	"RPG in a Box <https://www.rpginabox.com>",
	"Tiago Magalhães <https://azerkail.github.io/>",
	"TrampolineTales <https://TrampolineTales.com/>",
	"And 1 anonymous donor",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_PLATINUM[] = {
	"@reilaos",
	"Austin Hackett",
	"BlockImperiumGames (BIG)",
	"Bytten Studio",
	"Caspar Kleijne",
	"Christopher Shifflett",
	"Cody Bentley",
	"Cristian P.",
	"Daniel Cooper",
	"Darrin Massena",
	"DrDeadlock",
	"Emergo Entertainment",
	"Eric Burns",
	"Fabio Alessandrelli",
	"Francis Nguyen",
	"Fresh Fineapple",
	"GrammAcc",
	"HP van Braam",
	"Huge Workshop",
	"iCommitGames",
	"Jason Hamilton",
	"Jeremy Blouir",
	"Jonah Stich",
	"Josh Anthony",
	"k1r4n8",
	"Ludvig Temperli Risan",
	"Matthew Ekenstedt",
	"Memories in 8Bit",
	"Mike King",
	"Neal Gompa (Conan Kudo)",
	"Nikita Blizniuk",
	"Raptor85",
	"Rémi Verschelde",
	"Ryan Heath",
	"Sacha & Solène Waked",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"Stephan Kessler",
	"Stephen Rice",
	"theysayheygreg",
	"Walaber Entertainment",
	"And 8 anonymous donors",
	nullptr,
};

inline constexpr const char *DONORS_MEMBERS_GOLD[] = {
	"2 Nerdy Nerds",
	"73unny",
	"80px",
	"A. Friedman",
	"Abigail F.",
	"Admiral Potato",
	"Ajat BlackSun",
	"Alex177Alex",
	"alMoo Games",
	"Alnis Smidchens",
	"Alva Majo",
	"Ammerfest",
	"Amritpal Gill",
	"Andrea Monzini",
	"AndreasOM",
	"Andrew Eiche",
	"Andrew Zah",
	"Anfinor Games",
	"Ariya Studio",
	"Asher Glick",
	"Axthelm",
	"BangTheWall",
	"Ben Rog-Wilhelm",
	"Ben Sarsgard [Final Screw]",
	"Benito",
	"Benjamin Bridges",
	"Bryce Dixon",
	"Bäckdahl",
	"c64cosmin",
	"Carl van der Geest",
	"Carlo Cabanilla",
	"Carlo del Mundo",
	"Chaff Games",
	"Chamber of Light, Flower and Essence Incorporated*",
	"Chet Faliszek",
	"Chocolate Software",
	"Chris Backas",
	"Christian Mauduit",
	"Christian Sueiras",
	"Christine Elisabeth Koppel",
	"Cindy Trieu",
	"Codex404",
	"Conquintor",
	"cora",
	"Corey Robinson",
	"Crni Medved",
	"Daniel Eichler",
	"Daniel Krafft",
	"David Gehrig",
	"David Snopek",
	"Deakcor",
	"Delton Ding",
	"DIGITAL ILIAD",
	"Disco Cat",
	"Distorted Realities",
	"DitherDream",
	"Dominic Harris",
	"Dominik Frizel",
	"Don't You Know Who I Am? Inc.",
	"Dosimada",
	"DullyDev",
	"Dustuu",
	"Dylan Dromard",
	"Eamonn Irvine",
	"Edelweiss",
	"eelSkillz",
	"Ends",
	"Eric Brand",
	"Fail Forward Games",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"Felix Adam",
	"FeralBytes",
	"Frozen Fractal",
	"GeoScene",
	"GlassBrick",
	"Going Loud Studios",
	"Grau",
	"Grzegorz Wereszko",
	"Guangzhou Lingchan",
	"Hampas",
	"hiulit",
	"Holly Stubbs",
	"Huedeane",
	"Illyan",
	"Immaculate Lift Studio",
	"insomniacKoala",
	"Intrepid Marmot LLC",
	"Ione 15",
	"Isaac Clerencia",
	"Isaac Marovitz",
	"Isaac W",
	"Ivan Tabashki",
	"jakemiki",
	"Jason Cawood",
	"JAX691",
	"jeff compas",
	"Jeff Hungerford",
	"Jesús Chicharro",
	"JezerM",
	"Johannes Wuensch",
	"John Anders Stav",
	"John Brown",
	"Jonas Yamazaki",
	"Jonathan",
	"Jonathan Bass",
	"Jordan Chap",
	"Josh Jones",
	"Joshua OddBloom",
	"José Canepa",
	"Julian Todd",
	"Justin Laster",
	"Justin Sasso",
	"Kagia Benjamin",
	"Kalydi Balázs",
	"KAR Games",
	"Karl Bittner",
	"Kevin Morrell",
	"KOGA Mitsuhiro (@shiena)",
	"korinVR",
	"Kostya Stankevych",
	"Kristian Kriehl",
	"KyletheDab",
	"Lars Thießen",
	"LavishBehemoth",
	"Lee Ingram",
	"Leo Fruehstueck",
	"Lisandro Lorea (Red Mage Games)",
	"Logan Apple",
	"Los Lecheros Maincreros",
	"LoveCraftStudio.AI",
	"Luca Junge",
	"Luca Vazzano",
	"Luke_Username",
	"Lyaaaaa Games",
	"m1n1ster",
	"Madison Nicole Videogames",
	"Manul Opus",
	"Mara Huldra",
	"Mara Huldra",
	"Marcos Vinícius Marcon (Krakaton Games)",
	"Marek Belski",
	"Maskerade Games",
	"Matthias B.",
	"Meanwhile SRL",
	"Michael Alexsander",
	"Michael Gooch",
	"Miguel RS Gonçalves",
	"Mike Matthews",
	"Miles(Wedomi Games)",
	"Modus Ponens",
	"Moshe Harris",
	"Moth Soup",
	"Mr. Byte",
	"Nassor Paulino da Silva",
	"NEKERAFA",
	"nezticle",
	"Nicolas Everhart",
	"Niklas Wahrman",
	"Nitzan Bueno",
	"NojuHD",
	"NotNet",
	"Officine Pixel",
	"ohanaya3",
	"Okatima AB",
	"ole-luk-oje",
	"Oscar Robin",
	"Osirisa",
	"osje44",
	"ovym",
	"Parade of Rain",
	"Patrick Forringer",
	"Patrick Traynor",
	"Paul Bettner",
	"PeakMaven - Stefan Langwald",
	"Pete Goodwin",
	"Peter Langmayr",
	"Petr Maláč",
	"Phobos001",
	"pirey",
	"Péter Horváth-Lázár",
	"Rafa Laguna",
	"re:thinc",
	"RedEye Games",
	"Reid Hannaford",
	"Request",
	"Ric Janus Sapasap",
	"Richard Ivánek",
	"Robin Six",
	"Rodz Labs",
	"Roelof Pieters",
	"Ronny Mühle",
	"Rubén Rüger",
	"Samuel Judd",
	"Santi_FC",
	"shazzner",
	"Sheeta Games",
	"Shifty The Dev",
	"Shiny Shinken",
	"Skie Radscale",
	"Sofox",
	"Space Kraken Studios",
	"Spencer Chang",
	"Spoony Panda",
	"Stormbrew",
	"Tanner Storment",
	"tenuki",
	"Terry Cavanagh",
	"terry kasey",
	"ThatGamer",
	"Thomas Kurz",
	"Thomas Lobig",
	"Tobias Bocanegra",
	"Tom Langwaldt",
	"Trevor Slocum",
	"tukon",
	"Twirlin' Curtis",
	"Uriel Campos",
	"Vincent Foulon",
	"Vivian Rodríguez Saseta",
	"Vojtech Lacina",
	"Watchinofoye",
	"Xelarender",
	"zikes",
	"Zoey Smith",
	"嗯大爷",
	"And 117 anonymous donors",
	nullptr,
};
